AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - '**/*.gemspec'
    - '*.gemspec'
  NewCops: enable
  SuggestExtensions: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 125
  AllowHeredoc: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false
