plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120
  AllowHeredoc: true

Layout/SpaceAroundOperators:
  Enabled: true
  EnforcedStyleForExponentOperator: space

Layout/SpaceInsideBlockBraces:
  Enabled: true
  SpaceBeforeBlockParameters: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 15

Metrics/PerceivedComplexity:
  Enabled: false

Style/BlockDelimiters:
  AllowedPatterns:
    - each
    - expect

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Performance/ChainArrayAllocation:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

