---
include:
- Rakefile
- Gemfile
- "*.gemspec"
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- ".bundle/**/*"
- "node_modules/**/*"
require: []
domains: []
reporters: []
formatter: []
require_paths: []
plugins: []
max_files: 3000
